services:
  app:
    build: .
    container_name: dotnet-app
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
      - redis
      - elasticsearch
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Port=5432;Database=hospitalDb;User Id=sa;Password=hospotal123@;Include Error Detail=true;
      - Redis__Connection=redis:6379
      - ElasticSearch__Url=http://elasticsearch:9200
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "hospotal123@"
      ACCEPT_EULA: "Y"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mynetwork
  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
